// src/constants/permissions.js

// High-level roles for staff users
const ROLES = {
  OPERATOR: "operator",
  AGENT: "agent",
  CASHIER: "cashier",
  DISTRIBUTOR: "distributor",
  OWNER: "owner",
};

// Fine-grained permissions
// NOTE: These are used by requirePermission() in staffAuth middleware.
const PERMISSIONS = {
  TENANT_MANAGE: "tenant:manage",
  STAFF_MANAGE: "staff:manage",

  PLAYER_READ: "player:read",
  PLAYER_WRITE: "player:write",

  FINANCE_READ: "finance:read",
  FINANCE_WRITE: "finance:write",

  BET_LOG_READ: "betlog:read",

  VOUCHER_READ: "voucher:read",
  VOUCHER_WRITE: "voucher:write",
  VOUCHER_TERMINATE: "voucher:terminate",

  // Owner-console / platform governance
  ORDER_MANAGE: "orders:manage",
  CONFIG_MANAGE: "config:manage",
  BRAND_MANAGE: "brand:manage",
};

// Default permissions per role
const ROLE_DEFAULT_PERMISSIONS = {
  [ROLES.OWNER]: [
    PERMISSIONS.TENANT_MANAGE,
    PERMISSIONS.STAFF_MANAGE,
    PERMISSIONS.PLAYER_READ,
    PERMISSIONS.PLAYER_WRITE,
    PERMISSIONS.FINANCE_READ,
    PERMISSIONS.FINANCE_WRITE,
    PERMISSIONS.BET_LOG_READ,
    PERMISSIONS.VOUCHER_READ,
    PERMISSIONS.VOUCHER_WRITE,
    PERMISSIONS.VOUCHER_TERMINATE,
    PERMISSIONS.ORDER_MANAGE,
    PERMISSIONS.CONFIG_MANAGE,
    PERMISSIONS.BRAND_MANAGE,
  ],
  [ROLES.OPERATOR]: [
    PERMISSIONS.TENANT_MANAGE,
    PERMISSIONS.STAFF_MANAGE,
    PERMISSIONS.PLAYER_READ,
    PERMISSIONS.PLAYER_WRITE,
    PERMISSIONS.FINANCE_READ,
    PERMISSIONS.FINANCE_WRITE,
    PERMISSIONS.BET_LOG_READ,
    PERMISSIONS.VOUCHER_READ,
    PERMISSIONS.VOUCHER_WRITE,
    PERMISSIONS.VOUCHER_TERMINATE,
  ],
  [ROLES.DISTRIBUTOR]: [
    // Tenant admin (same power level as operator in this product)
    PERMISSIONS.TENANT_MANAGE,
    PERMISSIONS.STAFF_MANAGE,
    PERMISSIONS.PLAYER_READ,
    PERMISSIONS.PLAYER_WRITE,
    PERMISSIONS.FINANCE_READ,
    PERMISSIONS.FINANCE_WRITE,
    PERMISSIONS.BET_LOG_READ,
    PERMISSIONS.VOUCHER_READ,
    PERMISSIONS.VOUCHER_WRITE,
    PERMISSIONS.VOUCHER_TERMINATE,
  ],
  [ROLES.AGENT]: [
    PERMISSIONS.PLAYER_READ,
    PERMISSIONS.PLAYER_WRITE,
    PERMISSIONS.FINANCE_READ,
    PERMISSIONS.FINANCE_WRITE,
    PERMISSIONS.BET_LOG_READ,
    PERMISSIONS.VOUCHER_READ,
    PERMISSIONS.VOUCHER_WRITE,
    PERMISSIONS.VOUCHER_TERMINATE,
  ],
  [ROLES.CASHIER]: [
    PERMISSIONS.PLAYER_READ,
    PERMISSIONS.FINANCE_READ,
    PERMISSIONS.FINANCE_WRITE,
    PERMISSIONS.VOUCHER_READ,
    PERMISSIONS.VOUCHER_WRITE,
    PERMISSIONS.VOUCHER_TERMINATE,
  ],
};

module.exports = {
  ROLES,
  PERMISSIONS,
  ROLE_DEFAULT_PERMISSIONS,
};
