// src/constants/permissions.js

// High-level roles for staff users
const ROLES = {
  OPERATOR: "operator",
  AGENT: "agent",
  CASHIER: "cashier",
  DISTRIBUTOR: "distributor",
  OWNER: "owner",
};

// Fine-grained permissions
const PERMISSIONS = {
  TENANT_MANAGE: "tenant:manage",
  STAFF_MANAGE: "staff:manage",

  PLAYER_READ: "player:read",
  PLAYER_WRITE: "player:write",

  FINANCE_READ: "finance:read",
  FINANCE_WRITE: "finance:write",

  BET_LOG_READ: "betlog:read",
};

// Default permissions per role
const ROLE_DEFAULT_PERMISSIONS = {
  [ROLES.OWNER]: [
    PERMISSIONS.TENANT_MANAGE,
    PERMISSIONS.STAFF_MANAGE,
    PERMISSIONS.PLAYER_READ,
    PERMISSIONS.PLAYER_WRITE,
    PERMISSIONS.FINANCE_READ,
    PERMISSIONS.FINANCE_WRITE,
    PERMISSIONS.BET_LOG_READ,
  ],
  [ROLES.OPERATOR]: [
    PERMISSIONS.TENANT_MANAGE,
    PERMISSIONS.STAFF_MANAGE,
    PERMISSIONS.PLAYER_READ,
    PERMISSIONS.PLAYER_WRITE,
    PERMISSIONS.FINANCE_READ,
    PERMISSIONS.FINANCE_WRITE,
    PERMISSIONS.BET_LOG_READ,
  ],
  [ROLES.AGENT]: [
    PERMISSIONS.PLAYER_READ,
    PERMISSIONS.PLAYER_WRITE,
    PERMISSIONS.FINANCE_READ,
    PERMISSIONS.FINANCE_WRITE,
    PERMISSIONS.BET_LOG_READ,
  ],
  [ROLES.DISTRIBUTOR]: [
    PERMISSIONS.PLAYER_READ,
    PERMISSIONS.FINANCE_READ,
  ],
  [ROLES.CASHIER]: [
    PERMISSIONS.PLAYER_READ,
    PERMISSIONS.FINANCE_WRITE,
  ],
};

module.exports = {
  ROLES,
  PERMISSIONS,
  ROLE_DEFAULT_PERMISSIONS,
};
